import Head from 'next/head'
import { Inter } from 'next/font/google'
import { clsx } from 'clsx';
import NavBarItem from './ccommon/NavBarItem/NavBarItem';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-back-100'>
      <nav className="flex h-screen w-{264px} bg-back-100">
      <div >
        <h2 className="text-xs pl-2 text-font-100"> Games</h2>
        <div>
          <NavBarItem text="Coin flip" />
        </div>
       </div>
      </nav>
      </main>
    </>
  )
}
